// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chemicals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChemical = `-- name: CreateChemical :one
INSERT INTO chemicals (name, cas_number, formula, sds_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, cas_number, formula, sds_url, created_at
`

type CreateChemicalParams struct {
	Name      string      `json:"name"`
	CasNumber pgtype.Text `json:"cas_number"`
	Formula   pgtype.Text `json:"formula"`
	SdsUrl    pgtype.Text `json:"sds_url"`
}

func (q *Queries) CreateChemical(ctx context.Context, arg CreateChemicalParams) (Chemical, error) {
	row := q.db.QueryRow(ctx, createChemical,
		arg.Name,
		arg.CasNumber,
		arg.Formula,
		arg.SdsUrl,
	)
	var i Chemical
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CasNumber,
		&i.Formula,
		&i.SdsUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listChemicals = `-- name: ListChemicals :many
SELECT id, name, cas_number, formula, sds_url, created_at
FROM chemicals
ORDER BY id
`

func (q *Queries) ListChemicals(ctx context.Context) ([]Chemical, error) {
	rows, err := q.db.Query(ctx, listChemicals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chemical
	for rows.Next() {
		var i Chemical
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CasNumber,
			&i.Formula,
			&i.SdsUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChemicals = `-- name: SearchChemicals :many
SELECT id, name, cas_number, formula, sds_url, created_at
FROM chemicals
WHERE
    ($1::text IS NULL OR name ILIKE '%' || $1 || '%'
     OR cas_number ILIKE '%' || $1 || '%'
     OR formula ILIKE '%' || $1 || '%')
ORDER BY name
`

func (q *Queries) SearchChemicals(ctx context.Context, dollar_1 string) ([]Chemical, error) {
	rows, err := q.db.Query(ctx, searchChemicals, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chemical
	for rows.Next() {
		var i Chemical
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CasNumber,
			&i.Formula,
			&i.SdsUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
