// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: containers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkoutContainer = `-- name: CheckoutContainer :one
UPDATE containers
SET status = 'checked_out',
    checked_out_by = $2
WHERE id = $1
RETURNING id, chemical_id, room_id, label_code, quantity, unit, status, checked_out_by, created_at
`

type CheckoutContainerParams struct {
	ID           int64       `json:"id"`
	CheckedOutBy pgtype.Int8 `json:"checked_out_by"`
}

func (q *Queries) CheckoutContainer(ctx context.Context, arg CheckoutContainerParams) (Container, error) {
	row := q.db.QueryRow(ctx, checkoutContainer, arg.ID, arg.CheckedOutBy)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.ChemicalID,
		&i.RoomID,
		&i.LabelCode,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.CheckedOutBy,
		&i.CreatedAt,
	)
	return i, err
}

const createContainer = `-- name: CreateContainer :one
INSERT INTO containers (chemical_id, room_id, label_code, quantity, unit, status, checked_out_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, chemical_id, room_id, label_code, quantity, unit, status, checked_out_by, created_at
`

type CreateContainerParams struct {
	ChemicalID   int64       `json:"chemical_id"`
	RoomID       int64       `json:"room_id"`
	LabelCode    pgtype.Text `json:"label_code"`
	Quantity     float64     `json:"quantity"`
	Unit         string      `json:"unit"`
	Status       string      `json:"status"`
	CheckedOutBy pgtype.Int8 `json:"checked_out_by"`
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) (Container, error) {
	row := q.db.QueryRow(ctx, createContainer,
		arg.ChemicalID,
		arg.RoomID,
		arg.LabelCode,
		arg.Quantity,
		arg.Unit,
		arg.Status,
		arg.CheckedOutBy,
	)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.ChemicalID,
		&i.RoomID,
		&i.LabelCode,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.CheckedOutBy,
		&i.CreatedAt,
	)
	return i, err
}

const filterContainers = `-- name: FilterContainers :many
SELECT id, chemical_id, room_id, label_code, quantity, unit, status, checked_out_by, created_at
FROM containers
WHERE
    ($1 = '' OR status = $1)
  AND
    ($2 = 0 OR room_id = $2)
ORDER BY id
`

type FilterContainersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) FilterContainers(ctx context.Context, arg FilterContainersParams) ([]Container, error) {
	rows, err := q.db.Query(ctx, filterContainers, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.ChemicalID,
			&i.RoomID,
			&i.LabelCode,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.CheckedOutBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainers = `-- name: ListContainers :many
SELECT id, chemical_id, room_id, label_code, quantity, unit, status, checked_out_by, created_at
FROM containers
ORDER BY id
`

func (q *Queries) ListContainers(ctx context.Context) ([]Container, error) {
	rows, err := q.db.Query(ctx, listContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.ChemicalID,
			&i.RoomID,
			&i.LabelCode,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.CheckedOutBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnContainer = `-- name: ReturnContainer :one
UPDATE containers
SET status = 'available',
    checked_out_by = NULL
WHERE id = $1
RETURNING id, chemical_id, room_id, label_code, quantity, unit, status, checked_out_by, created_at
`

func (q *Queries) ReturnContainer(ctx context.Context, id int64) (Container, error) {
	row := q.db.QueryRow(ctx, returnContainer, id)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.ChemicalID,
		&i.RoomID,
		&i.LabelCode,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.CheckedOutBy,
		&i.CreatedAt,
	)
	return i, err
}
