// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chemical struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CasNumber pgtype.Text        `json:"cas_number"`
	Formula   pgtype.Text        `json:"formula"`
	SdsUrl    pgtype.Text        `json:"sds_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Container struct {
	ID           int64              `json:"id"`
	ChemicalID   int64              `json:"chemical_id"`
	RoomID       int64              `json:"room_id"`
	LabelCode    pgtype.Text        `json:"label_code"`
	Quantity     float64            `json:"quantity"`
	Unit         string             `json:"unit"`
	Status       string             `json:"status"`
	CheckedOutBy pgtype.Int8        `json:"checked_out_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Employee struct {
	ID        int64              `json:"id"`
	FullName  string             `json:"full_name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
